# Generated by Django 5.2.7 on 2025-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='xls_form',
            field=models.FileField(blank=True, null=True, upload_to='xlsforms/'),
        ),
    ]
