/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CardHeader: typeof import('./components/ui/CardHeader.vue')['default']
    ChoicesHotTable: typeof import('./components/ChoicesHotTable.vue')['default']
    DefaultHotTable: typeof import('./components/DefaultHotTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileModal: typeof import('./components/FileModal.vue')['default']
    FormField: typeof import('./components/ui/FormField.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    Link: typeof import('./components/ui/Link.vue')['default']
    Modal: typeof import('./components/ui/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsHotTable: typeof import('./components/SettingsHotTable.vue')['default']
    Snackbar: typeof import('./components/ui/Snackbar.vue')['default']
    StatusText: typeof import('./components/ui/StatusText.vue')['default']
    SurveyHotTable: typeof import('./components/SurveyHotTable.vue')['default']
    Table: typeof import('./components/ui/Table.vue')['default']
    TableCell: typeof import('./components/ui/TableCell.vue')['default']
    TableHeader: typeof import('./components/ui/TableHeader.vue')['default']
    Textarea: typeof import('./components/ui/Textarea.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Tooltip: typeof import('./components/ui/Tooltip.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
